import { Emirates } from "@/types";

const emirates: Emirates = {
  AbuDhabi: {
    districts: [
      "Abu Dhabi City",
      "Al Ain",
      "Al Khalidiya",
      "Al Raha",
      "Saadiyat Island",
      "Yas Island",
      "Al Maryah Island",
      "Al Reef",
      "Masdar City",
      "Khalifa City",
      "Mussafah",
      "Bani Yas",
      "Al Dhafra",
      "Al Muroor",
      "Al Shamkha",
    ],
  },
  Dubai: {
    districts: [
      "Downtown Dubai",
      "Dubai Marina",
      "Jumeirah",
      "Deira",
      "Bur Dubai",
      "Al Barsha",
      "Al Qusais",
      "Dubai International City",
      "Dubai Silicon Oasis",
      "Dubai Sports City",
      "Dubai Motor City",
      "Dubai Investment Park",
      "Dubai Media City",
      "Dubai Internet City",
      "Dubai Knowledge Park",
      "Dubai Healthcare City",
      "Dubai Festival City",
      "Jumeirah Lake Towers",
      "Business Bay",
      "Nad Al Sheba",
    ],
  },
  Sharjah: {
    districts: [
      "Al Nahda",
      "Al Majaz",
      "Al Qasba",
      "Al Taawun",
      "Al Khan",
      "Al Mamzar",
      "Al Yarmook",
      "Al Jazzat",
      "Al Noaf",
      "Al Qulayaa",
      "Al Fayha",
      "Al Nud",
      "Al Ramla",
      "Al Hazana",
      "Al Mahatah",
      "Al Rolla",
      "Al Mirgab",
      "Al Shuwaihean",
      "Al Ghubaiba",
      "Al Tai",
      "Al Ramaqia",
      "Al Azra",
    ],
  },
  Ajman: {
    districts: [
      "Ajman City",
      "Al Nuaimiya",
      "Al Rashidiya",
      "Al Jurf",
      "Al Hamidiyah",
      "Al Rawda",
      "Al Mowaihat",
      "Al Zahra",
      "Al Rumailah",
      "Al Naemiyah",
      "Al Bustan",
      "Al Manama",
      "Al Jerf",
      "Al Nakhil",
      "Al Owan",
    ],
  },
  "Umm Al Quwain": {
    districts: [
      "Umm Al Quwain City",
      "Al Salamah",
      "Al Raas",
      "Al Riqqah",
      "Al Kharran",
      "Al Maidan",
      "Falaj Al Mualla",
      "Al Soor",
      "Al Dar Al Baida",
      "Al Raudah",
      "Al Salam City",
      "Al Haditha",
      "Al Sinniyah Island",
      "Al Ittihad Park",
      "Al Daib",
    ],
  },
  "Ras Al Khaimah": {
    districts: [
      "Ras Al Khaimah City",
      "Al Nakheel",
      "Al Dhait",
      "Al Mamourah",
      "Al Rams",
      "Al Hamra",
      "Al Jazeera Al Hamra",
      "Mina Al Arab",
      "Julphar",
      "Shamal",
      "Al Turfa",
      "Al Uraibi",
      "Al Kharran",
      "Al Rams Marine",
      "Al Dhaith",
    ],
  },
  Fujairah: {
    districts: [
      "Fujairah City",
      "Dibba Al Fujairah",
      "Al Faseel",
      "Al Gurfa",
      "Al Taween",
      "Al Hayl",
      "Al Bidiyah",
      "Al Aqqah",
      "Al Hail",
      "Masafi",
      "Murayrah",
      "Sharm",
      "Dhadna",
      "Al Halah",
      "Dadna",
    ],
  },
};
export default emirates;
